blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/nisalgunawardhana/security-checker-agent/discussions
    about: Join our community discussions for general questions, ideas, and feedback
  - name: 📧 Direct Contact
    url: mailto:contact@getasyntax.dev
    about: For security concerns or private inquiries, email the developer directly
  - name: 🔒 OWASP Resources
    url: https://owasp.org/Top10/
    about: Learn more about OWASP Top 10 security guidelines and best practices
